{
 "title": "Model Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Model Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "# Model Predictions\n\nThis model is responsible for predicting \nthe quality of wine given a number of chemical \nattributes. The scores range from 0-10 where\n0 is the worst and 10 is the best."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Model Score (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(regression_model_output_sum[30m]))  / sum(increase(regression_model_output_count[30m]))"
    }
   ]
  },
  {
   "title": "Model Prediction Distribution (30m avg)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(regression_model_output_bucket[30m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "options": {
    "content": "# Request Throughput\n\n2xx status codes denote a successful model\nprediction.\n\n4xx status codes are common when clients\nPOST data that does not meet the expected\nschema.\n\nWe calculate the success rate as the percentage\nof HTTP requests that do not return a 5xx code."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Success Rate (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_count_total{http_status=\"200\", exported_endpoint='/predict'}[30m])) / sum(increase(request_count_total{exported_endpoint='/predict'}[30m]))"
    }
   ]
  },
  {
   "title": "Requests (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(request_latency_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "options": {
    "content": "# Request Latencies\n\nWe have two SLOs for API latency:\n- Average latency SLO is breached if p50\nlatencies exceed 50ms for 5 minutes.\n- Extreme latency SLO is breached if p99\nlatencies exceed 300ms for 5 minutes.        "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    rate(request_latency_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(\n    rate(request_latency_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum(\n    rate(request_latency_seconds_bucket[1m])\n  ) by (le)\n)",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}